### ISSUE TITLE
정답만들기

### ISSUE THREAD

**Issue by yjh0816** [JakeUGT/numguess#1]
## 요약
numguess에서 쓰일 정답을 생성합니다.
정답조건: 1~100 사이의 정수

## 할일
- [x] randint import하기
- [x] randint 를 활용하여 임의의 정수 생성하기
- [x] 생성된 정수를 answer에 할당하기
- [x] (for debugging) console에 출력하기

**Comment by JakeUGT** [comment]
Thks mate
