### ISSUE TITLE
Computational Thinking

### ISSUE THREAD

**Issue by JakeUGT** [JakeUGT/numguess#3]
## 문제정의
한문장으로 정의할것
운동을 쉬었더니 살찌고 근손실 남 

## 문제분해
각 상황별 선택지들을 나열하시오
A. 지금 시간이 몇시지?
 - A. 오후 9시 후
 - B 오후 9시 전
   ㄴB-a : 오늘 일정이 오후 8시전에 끝났다 
   ㄴB-b : 오늘 일정이 오후 8시후에 끝났다 (스킵)

## 문제 추상화
B-a의 경우 : 
        ㄴ> B-a-1 : 오늘 일정이 오후 6시 전에 끝났다 
            -- (무산소 + 유산소)
        ㄴ> B-a-2 : 오늘 일정이 오후 6시~8시 사이에 끝났다 
            -- (유산소 only) 

## 솔루션

![예](https://user-images.githubusercontent.com/122242489/211467227-bcd7cd86-9847-463b-a6e4-71eabd3292b9.PNG)

**Comment by yjh0816** [comment]
Well done. I hope you will be healty :)
